### PR TITLE
Styling_v2

### PR DESCRIPTION
**Pull request by AbreezaSaleem**

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Hey @AbreezaSaleem, the image pipeline is more complicated than it is required here. Can you simply use the "StaticImage" method instead? Also, depending on the locale just change the image within the components.

Screenshot 2021-04-25 at 3 52 11 PM

**Comment by AbreezaSaleem** [comment]
> Hey @AbreezaSaleem, the image pipeline is more complicated than it is required here. Can you simply use the "StaticImage" method instead? Also, depending on the locale just change the image within the components.
> 
> Screenshot 2021-04-25 at 3 52 11 PM

I wanted to use static images but I couldn’t use static images because they need to know the source of the image at build time. Only hardcoded paths that will not change at runtime will work for them. 

If this is too complicated that maybe we can do something like:
`locale === arabic ? <StaticImage1/> : <StaticImage2/>`

And for the sample images we can render the image directly from the `index` file instead of mapping the `SAMPLE_DATA` and passing the image as props to the Card component.

**Comment by abdulrauf11** [comment]
@AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?

Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?

**Comment by AbreezaSaleem** [comment]
> @AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?
> 
> Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?

It will be less complicated but there will be more duplication. Let me just test the second approach and see if it works fine then we can decide which one to go for. 

I wasn't able to reproduce the lag locally either. You will need to set the speed to Slow 3G in the networks tab to be able to reproduce it.

P.s umm I was talking about both the lag and the animation delay. It takes a few seconds for the image to display and when it does it fades in slowly too.

**Comment by abdulrauf11** [comment]
> > @AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?
> > Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?
> 
> It will be less complicated but there will be more duplication. Let me just test the second approach and see if it works fine then we can decide which one to go for.
> 
> I wasn't able to reproduce the lag locally either. You will need to set the speed to Slow 3G in the networks tab to be able to reproduce it.

How about we just write functions (similar to the image I sent above) and then return those components depending on id maybe. Will that work? We do know there cannot be more than 3 images in the "SamplePlayer" which means 3 one-line functions at max.

**Comment by AbreezaSaleem** [comment]
> > > @AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?
> > > Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?
> > 
> > 
> > It will be less complicated but there will be more duplication. Let me just test the second approach and see if it works fine then we can decide which one to go for.
> > I wasn't able to reproduce the lag locally either. You will need to set the speed to Slow 3G in the networks tab to be able to reproduce it.
> 
> How about we just write functions (similar to the image I sent above) and then return those components depending on id maybe. Will that work? We do know there cannot be more than 3 images in the "SamplePlayer".

Writing one functional component for all three images won't work because we're deciding which image path to put in the src via the id. What we can do is write separate components for the three images? Btw, this is the current approach:

```
     <Card
          key={SAMPLE_DATA[0].id}
          id={SAMPLE_DATA[0].id}
          sample={SAMPLE_DATA[0].data}
          imageComp={(
            <StaticImage
              src="../../../utils/images/samples/bird.png"
              alt="sample-image"
              style={{ display: 'block', height: 221 }}
              loading="eager"
            />
          )}
          text={SAMPLE_DATA[0].text}
          toggleAudio={toggleAudio}
        />
        <Card
          key={SAMPLE_DATA[1].id}
          id={SAMPLE_DATA[1].id}
          sample={SAMPLE_DATA[1].data}
          imageComp={(
            <StaticImage
              src="../../../utils/images/samples/traffic.png"
              alt="sample-image"
              style={{ display: 'block', height: 221 }}
              loading="eager"
            />
          )}
          text={SAMPLE_DATA[1].text}
          toggleAudio={toggleAudio}
        />
        <Card
          key={SAMPLE_DATA[2].id}
          id={SAMPLE_DATA[2].id}
          sample={SAMPLE_DATA[2].data}
          imageComp={(
            <StaticImage
              src="../../../utils/images/samples/anthem.png"
              alt="sample-image"
              style={{ display: 'block', height: 221 }}
              loading="eager"
            />
          )}
          text={SAMPLE_DATA[2].text}
          toggleAudio={toggleAudio}
        />
```

I can replace the SAMPLE_DATA with the actual data.

**Comment by AbreezaSaleem** [comment]
> > > @AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?
> > > Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?
> > 
> > 
> > It will be less complicated but there will be more duplication. Let me just test the second approach and see if it works fine then we can decide which one to go for.
> > I wasn't able to reproduce the lag locally either. You will need to set the speed to Slow 3G in the networks tab to be able to reproduce it.
> 
> How about we just write functions (similar to the image I sent above) and then return those components depending on id maybe. Will that work? We do know there cannot be more than 3 images in the "SamplePlayer".

Let me try this.

**Comment by AbreezaSaleem** [comment]
> > > @AbreezaSaleem Good point! Do you think it will be less complicated the way you're suggesting now?
> > > Also, I couldn't reproduce the lag (while the image is loading) you were referring to on Discord. Do you mean the animation-delay when it fades in?
> > 
> > 
> > It will be less complicated but there will be more duplication. Let me just test the second approach and see if it works fine then we can decide which one to go for.
> > I wasn't able to reproduce the lag locally either. You will need to set the speed to Slow 3G in the networks tab to be able to reproduce it.
> 
> How about we just write functions (similar to the image I sent above) and then return those components depending on id maybe. Will that work? We do know there cannot be more than 3 images in the "SamplePlayer" which means 3 one-line functions at max.

Pushed a commit. Let me know if that approach works for you.

**Comment by abdulrauf11** [comment]
Yes seems good enough 👍

Do you want me to merge now or are there still changes to be made in this PR?

**Comment by AbreezaSaleem** [comment]
Give me 15 minutes to remove the unwanted files and then you can merge it.

**Pull request merged**
