### PR TITLE
Change requests for voice recorder

### PR DESCRIPTION
**Pull request by AbreezaSaleem**

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Perfect!

Can you make one change though? The trash button should be active while you are playing the recording. Clicking on that will delete the recording and the user can start over.

**Comment by AbreezaSaleem** [comment]
> Perfect!
> 
> Can you make one change though? The trash button should be active while you are playing the recording. Clicking on that will delete the recording and the user can start over.

Isn't this already happening? I just checked on my end and its working as expected, can you please check again?

**Comment by abdulrauf11** [comment]
For me when I'm playing (green bar) all the buttons are inactive.

Screenshot 2021-04-18 at 8 23 02 PM

**Comment by AbreezaSaleem** [comment]
> For me when I'm playing (green bar) all the buttons are inactive.
> 
> Screenshot 2021-04-18 at 8 23 02 PM

Oh right I thought this requirement was for when we're making a recording, not playing it back. So just to be clear, we want the trash button to be active during both recording and playback and clicking on it will delete the current audio?

**Pull request merged**
