### PR TITLE
Milestone#6 Issues

### PR DESCRIPTION
**Pull request by AbreezaSaleem**

### CODE REVIEW

**Comment by abdulrauf11** [comment]
1. Why did we use focus-visible instead of focus? I'm not sure about the difference myself.
2. Can we add the button:active (it should fade on click like other buttons) state while we're playing/stopping the recorder audio.
3. Can you explain what you did for this issue: "Ability to interrupt playback/recordings" (https://github.com/scimusmn/tsck-cochlear-implant/issues/37)

I'll look into the gatsby issue.


EDIT: As far as point 3 is concerned, I have a little confusion about its second part. I've asked the client for clarification.

**Comment by AbreezaSaleem** [comment]
> 1. Why did we use focus-visible instead of focus? I'm not sure about the difference myself.
> 2. Can we add the button:active (it should fade on click like other buttons) state while we're playing/stopping the recorder audio.
> 3. Can you explain what you did for this issue: "Ability to interrupt playback/recordings" ([scimusmn#37](https://github.com/scimusmn/tsck-cochlear-implant/issues/37))
> 
> I'll look into the gatsby issue.
> 
> EDIT: As far as point 3 is concerned, I have a little confusion about its second part. I've asked the client for clarification.

1. I'm not sure either but I used `focus` first and when I went into the inspect mode to test it, there was no outline showing up in any case. But when I enforced `focus-visible`, it showed up. 
2. We should! It should have been implemented on its own though when we added the active states. I'll look into it.
3. I made use of the `AudioContext` API here. I added listeners for both the recorder and the samples section that check if the user plays a pre-recorded audio while a recorded audio is playing back then the application cancels the recording and plays the pre-recorded audio and vice versa.

**Comment by abdulrauf11** [comment]
> > 1. Why did we use focus-visible instead of focus? I'm not sure about the difference myself.
> > 2. Can we add the button:active (it should fade on click like other buttons) state while we're playing/stopping the recorder audio.
> > 3. Can you explain what you did for this issue: "Ability to interrupt playback/recordings" ([scimusmn#37](https://github.com/scimusmn/tsck-cochlear-implant/issues/37))
> > 
> > I'll look into the gatsby issue.
> > EDIT: As far as point 3 is concerned, I have a little confusion about its second part. I've asked the client for clarification.
> 
> 1. I'm not sure either but I used `focus` first and when I went into the inspect mode to test it, there was no outline showing up in any case. But when I enforced `focus-visible`, it showed up.
> 2. We should! It should have been implemented on its own though when we added the active states. I'll look into it.
> 3. I made use of the `AudioContext` API here. I added listeners for both the recorder and the samples section that check if the user plays a pre-recorded audio while a recorded audio is playing back then the application cancels the recording and plays the pre-recorded audio and vice versa.

1. Is there a case where the outline should appear? From the issue's description, it seems they don't want the outline to appear in any case.

**Comment by AbreezaSaleem** [comment]
> > > 1. Why did we use focus-visible instead of focus? I'm not sure about the difference myself.
> > > 2. Can we add the button:active (it should fade on click like other buttons) state while we're playing/stopping the recorder audio.
> > > 3. Can you explain what you did for this issue: "Ability to interrupt playback/recordings" ([scimusmn#37](https://github.com/scimusmn/tsck-cochlear-implant/issues/37))
> > > 
> > > I'll look into the gatsby issue.
> > > EDIT: As far as point 3 is concerned, I have a little confusion about its second part. I've asked the client for clarification.
> > 
> > 
> > 
> > 1. I'm not sure either but I used `focus` first and when I went into the inspect mode to test it, there was no outline showing up in any case. But when I enforced `focus-visible`, it showed up.
> > 2. We should! It should have been implemented on its own though when we added the active states. I'll look into it.
> > 3. I made use of the `AudioContext` API here. I added listeners for both the recorder and the samples section that check if the user plays a pre-recorded audio while a recorded audio is playing back then the application cancels the recording and plays the pre-recorded audio and vice versa.
> 
> 1. Is there a case where the outline should appear? From the issue's description, it seems they don't want the outline to appear in any case.

Yeah I was testing my code. It won't appear now. It was appearing only when the `focus-visible` was enforced.

**Comment by abdulrauf11** [comment]
@AbreezaSaleem Okay cool! Let's just add both (focus and focus-visible) to be on the safe side.

**Comment by AbreezaSaleem** [comment]
> @AbreezaSaleem Okay cool! Let's just add both (focus and focus-visible) to be on the safe side.

okay!

**Comment by AbreezaSaleem** [comment]
> > @AbreezaSaleem Okay cool! Let's just add both (focus and focus-visible) to be on the safe side.
> 
> okay!

@abdulrauf11  done

**Comment by abdulrauf11** [comment]
> > > @AbreezaSaleem Okay cool! Let's just add both (focus and focus-visible) to be on the safe side.
> > 
> > 
> > okay!
> 
> @abdulrauf11 done

The active state for the buttons as well?

**Comment by abdulrauf11** [comment]
@AbreezaSaleem  Nice work! A few changes to the "Ability to interrupt playback/recordings" issue:

1. When a user is recording, the sample player should not show its disabled state since it can interrupt the recorder now.
2. Playing a pre-recorded sound from the sample player should reset the recorder, whether you are recording or playing the sound. Right now it only cancels when you are playing it back and not while you're recording.

Let me know if it's clear.

**Comment by AbreezaSaleem** [comment]
> @AbreezaSaleem Nice work! A few changes to the "Ability to interrupt playback/recordings" issue:
> 
> 1. When a user is recording, the sample player should not show its disabled state since it can interrupt the recorder now.
> 2. Playing a pre-recorded sound from the sample player should reset the recorder, whether you are recording or playing the sound. Right now it only cancels when you are playing it back and not while you're recording.
> 
> Let me know if it's clear.

I've made the requested changes. Both the stopping of the recording and the active state issue in the sample recorder buttons. Please review.

**Comment by abdulrauf11** [comment]
Nice work! But I think the recording should also be cancelled in this case (when it has been recorded completely):
Screenshot 2021-05-18 at 7 18 45 PM

EDIT: Let me confirm this from the client as well.

**Comment by AbreezaSaleem** [comment]
> Nice work! But I think the recording should also be cancelled in this case (when it has been recorded completely):
> Screenshot 2021-05-18 at 7 18 45 PM

Oh okay let me see.

**Comment by abdulrauf11** [comment]
@AbreezaSaleem  You can wait on implementing this but the first case was not successful in this push (when a user is recording and they play one of the pre-recorded sounds)

Screenshot 2021-05-18 at 7 30 22 PM

**Comment by abdulrauf11** [comment]
Awesome thanks!

**Pull request merged**
