### PR TITLE
Final styling

### PR DESCRIPTION
**Pull request by AbreezaSaleem**

### CODE REVIEW

**Comment by abdulrauf11** [comment]
Good work so far! Can you keep the module.scss names the same as component names to avoid any confusion?

Also, the fonts seem the same to me. Maybe the font weight is not exact which is why it looks a little different.

**Comment by AbreezaSaleem** [comment]
> Good work so far! Can you keep the module.scss names the same as component names to avoid any confusion?
> 
> Also, the fonts seem the same to me. Maybe the font weight is not exact which is why it looks a little different.

Sure! I'll change the file names. And the font-weight tip is good, I'll also tweak the weights and see if they match the design.

**Comment by abdulrauf11** [comment]
I am getting an error regarding a missing image. Please confirm if that's the case.

Screenshot 2021-04-13 at 11 36 26 PM

**Comment by AbreezaSaleem** [comment]
> I am getting an error regarding a missing image. Please confirm if that's the case.
> 
> Screenshot 2021-04-13 at 11 36 26 PM

I missed pushing these images. Please take a pull and run it again

**Comment by abdulrauf11** [comment]
Good work! I'll try to mention the issues I could find below:

- [ ] 1. There are some issues with the sizes but that is understandable at this point and we will refine that in the end.
- [ ] 2. The images in the "Sample Player" section are stretched.
- [x] 3. The SVGs within the circles are not exactly in the center.
- [ ] 4. The modal part is not done yet but you've mentioned that you're still working on it. Just writing it here so I remember.
- [ ] 5. Make sure the sizes (border-width, border-radius, font-size etc) are similar to the ones used in Figma.
- [x] 6. In English, they are using two different fonts: Montserrat for the heading and Open Sans for text.
- [x] 7. Active state for the "Sample Player"
- [x] 8. I also recently noticed this and I don't think the Voice Recorder should work when audio from Sample Player is playing.

Let me know if you have any comments.

**Comment by AbreezaSaleem** [comment]
> Good work! I'll try to mention the issues I could find below:
> 
> 1. There are some issues with the sizes but that is understandable at this point and we will refine that in the end.
> 2. The images in the "Sample Player" section are stretched.
> 3. The SVGs within the circles are not exactly in the center.
> 4. The modal part is not done yet but you've mentioned that you're still working on it. Just writing it here so I remember.
> 
> Let me know if you have any comments.

Yeah I am aware of the svg + images getting stretched issues. Ca

**Comment by AbreezaSaleem** [comment]
> > Good work! I'll try to mention the issues I could find below:
> > 
> > 1. There are some issues with the sizes but that is understandable at this point and we will refine that in the end.
> > 2. The images in the "Sample Player" section are stretched.
> > 3. The SVGs within the circles are not exactly in the center.
> > 4. The modal part is not done yet but you've mentioned that you're still working on it. Just writing it here so I remember.
> > 
> > Let me know if you have any comments.
> 
> Yeah I am aware of the svg + images getting stretched issues. Are you referring to the font-size issue in your first point?

Also, I'm working on the modal rn. I'll hopefully push an update for it in an hour or two.

**Comment by abdulrauf11** [comment]
Also, I wanted to confirm if the sizes used are according to the Figma design. For example, I noticed that border-width used in the design 2px while we are using 1px. Similarly, the border-radius for the container is 20px but we are using 10px instead.

**Comment by AbreezaSaleem** [comment]
> Also, I wanted to confirm if the sizes used are according to the Figma design. For example, I noticed that border-width used in the design 2px while we are using 1px. Similarly, the border-radius for the container is 20px but we are using 10px instead.

Hmm no. I must have missed those. I'll make a round of checks to see if I'm using the sizes mentioned in figma. Can you add this point to your first comment?

**Comment by abdulrauf11** [comment]
> > > Good work! I'll try to mention the issues I could find below:
> > > 
> > > 1. There are some issues with the sizes but that is understandable at this point and we will refine that in the end.
> > > 2. The images in the "Sample Player" section are stretched.
> > > 3. The SVGs within the circles are not exactly in the center.
> > > 4. The modal part is not done yet but you've mentioned that you're still working on it. Just writing it here so I remember.
> > > 
> > > Let me know if you have any comments.
> > 
> > 
> > Yeah I am aware of the svg + images getting stretched issues. Are you referring to the font-size issue in your first point?
> 
> Also, I'm working on the modal rn. I'll hopefully push an update for it in an hour or two.

The overall size including the fonts as well. I know that depends on the screen we will use in the end. For example, on my screen, the boxes inside the SamplePlayer are wider. I think we should discuss how we need to think about this which is why I wanted to leave this for the end.

Screenshot 2021-04-14 at 12 08 42 AM

**Comment by AbreezaSaleem** [comment]
> > > > Good work! I'll try to mention the issues I could find below:
> > > > 
> > > > 1. There are some issues with the sizes but that is understandable at this point and we will refine that in the end.
> > > > 2. The images in the "Sample Player" section are stretched.
> > > > 3. The SVGs within the circles are not exactly in the center.
> > > > 4. The modal part is not done yet but you've mentioned that you're still working on it. Just writing it here so I remember.
> > > > 
> > > > Let me know if you have any comments.
> > > 
> > > 
> > > Yeah I am aware of the svg + images getting stretched issues. Are you referring to the font-size issue in your first point?
> > 
> > 
> > Also, I'm working on the modal rn. I'll hopefully push an update for it in an hour or two.
> 
> The overall size including the fonts as well. I know that depends on the screen we will use in the end. For example, on my screen, the boxes inside the SamplePlayer are wider. I think we should discuss how we need to think about this which is why I wanted to leave this for the end.
> 
> Screenshot 2021-04-14 at 12 08 42 AM

Oh this isn't looking good here. I'll need to revisit my approach for the sizes. Let's have a discussion on this at the end.

**Comment by abdulrauf11** [comment]
One main issue that I had was styling the components through the base.scss file. Since, we are using a modular approach those styles should come from the module files as well. However, the workflow was not designed that way and to solve that I wrote the following mixin:
```
@mixin localize($property, $ar-value, $en-value) {
    #{$property}: $ar-value;
    [class=en-us] & {
      #{$property}: $en-value;
    }
}
```

It can be used as:
```
@include localize(font-size, 22px, 20px);
```

The 1st argument is the property, the 2nd is the value applied to the Arabic layout (default) and the 3rd value is applied to the English layout.

I discussed it with the client and they only want the design to for 1920x1080 resolution so I changed the vh/vw values to px instead. Not sure if this was the right way to go about this but we'll discuss this later).


I also made the modal look like the Figma design. It became easier after using the mixin. Rest of the codebase is the same.

**Comment by abdulrauf11** [comment]
Make sure you run it like this for now to see the actual layout (as it is in pixels now):

Screenshot 2021-04-18 at 12 57 02 AM

**Pull request merged**
